blueprint:
  name: Default Volume - Room Independent
  description: >
    Adjusts speaker volume automatically based on input source:
    - If Optical input becomes active, sets to specified level
    - If Wifi input becomes active and Music Assistant is playing, sets to specified level
  domain: automation
  input:
    speaker_opt_sensor:
      name: Speaker Optical (Watch) Sensor
      description: ""
      selector:
        entity:
          domain: binary_sensor
    speaker_wifi_sensor:
      name: Speaker Wifi (Listen) Sensor
      description: ""
      selector:
        entity:
          domain: binary_sensor
    speaker_media_player:
      name: Speaker Media Player
      description: ""
      selector:
        entity:
          domain: media_player
    music_assistant_entity:
      name: Music Assistant Media Player
      description: ""
      selector:
        entity:
          domain: media_player
    watch_volume:
      name: Watch Activity Volume Default
      description: ""
      default: 0.48
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""
    listen_volume:
      name: Listen Activity Volume Default
      description: ""
      default: 0.45
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""

triggers:
  - platform: state
    id: "opt_input"
    entity_id: !input speaker_opt_sensor
    to: "on"
  - platform: state
    id: "wifi_input"
    entity_id: !input speaker_wifi_sensor
    to: "on"

mode: single

variables:
  speaker: !input speaker_media_player
  watch_volume_value: !input watch_volume
  listen_volume_value: !input listen_volume

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: "opt_input"
        sequence:
          - delay: "1"
          - condition: template
            value_template: >
              {{ state_attr(speaker, 'volume_level') | float != watch_volume_value }}
          - action: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: !input watch_volume

      - conditions:
          - condition: trigger
            id: "wifi_input"
        sequence:
          - delay: "1"
          - wait_for_trigger:
              - platform: state
                entity_id: !input music_assistant_entity
                to: "playing"
            timeout: "10"
            continue_on_timeout: false
          - condition: template
            value_template: >
              {{ state_attr(speaker, 'volume_level') | float != listen_volume_value }}
          - action: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: !input listen_volume
