blueprint:
  name: Default Volume - Source Based
  description: |
    Sets speaker volume on input changes only:
      - If source is 'Opt'  → set Watch volume
      - If source is 'Wifi' → set Listen volume (only if Music Assistant is playing)
  domain: automation

  input:
    watch_volume:
      name: Watch Default
      description: ""
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""
    listen_volume:
      name: Listen default
      description: ""
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""
    speaker_media_player:
      name: Speaker
      selector:
        entity:
          domain: media_player
    music_assistant_entity:
      name: Music Assistant
      selector:
        entity:
          domain: media_player

triggers:
  - platform: state
    entity_id: !input speaker_media_player
    attribute: source

mode: single

variables:
  speaker: !input speaker_media_player
  watch_volume_value: !input watch_volume
  listen_volume_value: !input listen_volume
  current_source: "{{ state_attr(speaker, 'source') }}"

actionss:
  - delay: "00:00:01"
  - choose:
      # Exact, case-sensitive: Opt → Watch volume
      - conditions:
          - condition: template
            value_template: "{{ current_source == 'Opt' }}"
        sequence:
          - action: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: "{{ watch_volume_value }}"

      # Exact, case-sensitive: Wifi → Listen volume, but only if MA is playing
      - conditions:
          - condition: template
            value_template: "{{ current_source == 'Wifi' }}"
          - condition: state
            entity_id: !input music_assistant_entity
            state: "playing"
        sequence:
          - action: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: "{{ listen_volume_value }}"
