blueprint:
  name: Default Volume - Room Independent
  description: |
    Adjusts speaker volume based on input source sensors:
    - Optical input → sets to level specified
    - WiFi + Music Assistant → sets to level specified
  
  domain: automation
  
  input:
    watch_volume:
      name: Watch Activity initial level
      description: ""
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""
    listen_volume:
      name: Listen Activity initial level
      description: ""
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider
          unit_of_measurement: ""
    speaker_opt_sensor:
      name: Speakers on Opt Sensor
      description: ""
      selector:
        entity:
          domain: binary_sensor
    speaker_wifi_sensor:
      name: Speakers on Wifi Sensor
      description: ""
      selector:
        entity:
          domain: binary_sensor
    speaker_media_player:
      name: Speakers
      description: ""
      selector:
        entity:
          domain: media_player
    music_assistant_entity:
      name: Music Assistant
      description: ""
      selector:
        entity:
          domain: media_player

triggers:
  - platform: state
    id: "opt_input"
    entity_id: !input speaker_opt_sensor
    to: "on"
  - platform: state
    id: "wifi_input"
    entity_id: !input speaker_wifi_sensor
    to: "on"

mode: single

variables:
  speaker: !input speaker_media_player
  watch_volume_value: !input watch_volume
  listen_volume_value: !input listen_volume

actions:
  - delay: "00:00:01"
  - choose:
      - conditions:
          - condition: trigger
            id: "opt_input"
        sequence:
          - action: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: !input watch_volume

      - conditions:
          - condition: trigger
            id: "wifi_input"
          - condition: state
            entity_id: !input music_assistant_entity
            state: "playing"
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: !input speaker_media_player
            data:
              volume_level: !input listen_volume
