blueprint:
  name: PiHub – Enact Activity (room-agnostic)
  description: >
    Enact watch/listen/power_off whenever the room's activity input_select changes.
    Updates the room's last_run input_select to the same value.
    Scripts are resolved by naming convention:
      - script.<room>_watch
      - script.<room>_listen
      - script.<room>_power_off
  domain: automation
  input:
    room:
      name: Room key
      description: Lowercase room id used in entity names (e.g. living_room)
      default: living_room
    activity_input_select:
      name: Activity input_select (current)
      selector:
        entity:
          domain: input_select
    last_run_input_select:
      name: Last-run input_select
      selector:
        entity:
          domain: input_select

mode: single

triggers:
  - trigger: state
    entity_id: !input activity_input_select

variables:
  # bind inputs to plain variables (so Jinja can use them)
  room: !input room
  activity_select: !input activity_input_select
  last_run_select: !input last_run_input_select

  # templated vars
  resolved: "{{ states(activity_select) }}"
  last_run: "{{ states(last_run_select) }}"

  # Script entity_ids derived from naming convention
  script_watch:  "{{ 'script.' ~ room ~ '_watch' }}"
  script_listen: "{{ 'script.' ~ room ~ '_listen' }}"
  script_power:  "{{ 'script.' ~ room ~ '_power_off' }}"

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ resolved == 'watch' }}"
        sequence:
          - service: script.turn_on
            target:
              entity_id: "{{ script_watch }}"
      - conditions:
          - condition: template
            value_template: "{{ resolved == 'listen' }}"
        sequence:
          - service: script.turn_on
            target:
              entity_id: "{{ script_listen }}"
      - conditions:
          - condition: template
            value_template: "{{ resolved == 'power_off' }}"
        sequence:
          - service: script.turn_on
            target:
              entity_id: "{{ script_power }}"

  - alias: Update last_run
    service: input_select.select_option
    target:
      entity_id: !input last_run_input_select
    data:
      option: "{{ resolved }}"

  - alias: Log enact
    service: logbook.log
    data:
      name: PiHub Enactor
      message: "Ran script for '{{ resolved }}' (room={{ room }})"
