blueprint:
  name: PiHub - Trigger Apple TV Power via MQTT
  description: >
    Publish Apple TV power commands to a room's PiHub.
    Sends either pihub/<room>/cmd/atv/on or .../off (QoS 1, retain false).
  domain: script
  input:
    room:
      name: Room key
      description: Room in snake_case, e.g. living_room
      selector:
        text:
    power:
      name: Power action
      selector:
        select:
          options:
            - on
            - off

sequence:
  - service: mqtt.publish
    data:
      topic: "pihub/{{ room }}/cmd/atv/{{ power }}"
      qos: 1
      retain: false

mode: single
