blueprint:
  name: Power Off (via MQTT Activity)
  description: |
    When MQTT receives 'power_off' on a specific topic, this automation:
    - updates activity
    - turns off the TV (if it's on)
    - turns off the speakers
    - resets Music Assistant
    - updates last run activity

  domain: automation

  input:
    mqtt_topic_rx:
      name: MQTT Topic Trigger e.g. pihub/<room>/activity
      description: ""
      selector:
        text: {}

    room_activity:
      name: Activity Input Select
      description: ""
      selector:
        entity:
          domain: input_select

    tv_sensor:
      name: TV Sensor
      description: ""
      selector:
        entity:
          domain: binary_sensor

    mqtt_topic_tx:
      name: MQTT Command Topic e.g. pihub/<room>/cmd
      description: ""
      selector:
        text: {}

    speakers:
      name: Speakers
      description: ""
      selector:
        entity:
          domain: media_player

    music_assistant_reset_script:
      name: Music Assistant Reset Script
      description: ""
      selector:
        entity:
          domain: script

    last_run_activity:
      name: Last Run Activity Input Select
      description: ""
      selector:
        entity:
          domain: input_select

triggers:
  - platform: mqtt
    topic: !input mqtt_topic_rx
    payload: "power_off"

condition: []

actions:
  - action: input_select.select_option
    target:
      entity_id: !input room_activity
    data:
      option: "power_off"

  - parallel:
      - choose:
          - conditions:
              - condition: state
                entity_id: !input tv_sensor
                state: "on"
            sequence:
              - action: mqtt.publish
                data:
                  topic: !input mqtt_topic_tx
                  payload: macro:atv-off
                  qos: "1"
                  retain: false

      - sequence:
          - action: media_player.turn_off
            target:
              entity_id: !input speakers

          - action: !input music_assistant_reset_script

  - action: input_select.select_option
    target:
      entity_id: !input last_run_activity
    data:
      option: "power_off"

mode: single
